version: 2
jobs:
  test:
    docker:
      - image: circleci/node:8.11

    working_directory: ~/ember-cli-deploy-ghpages

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-node-modules-{{ checksum "package.json" }}
            - v1-node-modules
      - run:
          name: Install dependencies
          command: npm install
      - save_cache:
          key: v1-node-modules-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run:
          name: Change Git user
          command: |
            git config user.email "support@verdigris.co"
            git config user.name "Verdigris Technologies"
      - run:
          name: Run tests
          command: npm test

workflows:
  version: 2
  feature-branch-test:
    jobs:
      - test:
          branches:
            ignore:
              - master
              - gh-pages
