version: 2
jobs:
  test:
    docker:
      - image: circleci/node:8.11

    working_directory: ~/ember-cli-deploy-ghpages

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-node-modules-{{ checksum "package.json" }}
            - v1-node-modules
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Run tests
          command: npm test
      - save_cache:
          key: v1-node-modules-{{ checksum "package.json" }}
          paths:
            - node_modules

workflows:
  version: 2
  feature-branch-test:
    jobs:
      - test:
          filters:
            branches:
              ignore: /master/
